FROM registry.lab.dynatrace.org/jci/jenkins-slave-lambda-python3.8:latest

ARG pypi_org_cache_repo=https://artifactory.lab.dynatrace.org/artifactory/api/pypi/pypi-org/simple

USER root

COPY dynatrace-aws-logs-ingest/src/requirements.txt /home/labuser/requirements.txt
COPY dynatrace-aws-logs-ingest/src/requirements-dev.txt /home/labuser/requirements-dev.txt

RUN pip3 install -r /home/labuser/requirements.txt -r /home/labuser/requirements-dev.txt -i $pypi_org_cache_repo
