pipeline {
    agent none
    stages {
        stage('PyLint and Unit Tests') {
            agent {
                dockerfile {
                    label 'docker'
                    filename 'dynatrace-aws-logs-ingest/pipeline/Dockerfile.build'
                }
            }
            stages {
                stage("PyLint") {
                    steps {
                        dir("dynatrace-aws-logs-ingest/src") {
                            sh 'python3 -m pylint --rcfile=../pipeline/pylint.cfg $(find . -name "*.py")'
                        }
                    }
                }
                stage("Unit Tests") {
                    steps {
                        dir("dynatrace-aws-logs-ingest/src") {
                            sh 'python3 -m pytest -v ../tests/unit'
                        }
                    }
                }
            }
        }
    }
}